title: Northwestern University PhD Student Advisory Council (CSPAC)
description: CSPAC is a PhD student organization representing all PhD students in the Computer Science(CS), Technology and Social Behavior(TSB), and Computer Science + Learning Science (CS+LS) graduat programs at Northwestern University.
show_downloads: true
theme: jekyll-theme-minimal